server {
    listen 80;
    server_name _;

    location /api/v1/dsp/ {
        proxy_pass http://controlplane:8084/api/v1/dsp/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/public/ {
        proxy_pass http://dataplane:8081/api/public/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /.well-known/api/ {
        proxy_pass http://controlplane:8085/.well-known/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        proxy_pass http://identityhub:8084;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
